[build]
  base = "cartify-main/client"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = "https://cartify-backend-production-a082.up.railway.app/api/:splat"
  status = 200
  force = true
